### ISSUE TITLE
If you feel this domain is wrongly blacklisted, please open a new issue on GitHub

### ISSUE THREAD

**Issue by Digital21** [409H/EtherAddressLookup#1042]
I hope this is a wrong step and create a trouble for the real users /innocence people, I request to support to resolve the issue.

https://mail.google.com/mail/u/0/#inbox/FMfcgxvzLrDsqngljrDSnKjpXCfMbgSM

**Comment by 409H** [comment]
Which domain is blacklisted? Are you reporting `mail.google.com` is? If so, I cannot replicate - can you provide screenshots

**Comment by Digital21** [comment]
1. working site - https://mail.google.com/mail/u/0/#inbox/FMfcgxvzLrDsqn
<img width="1440" alt="screenshot 2018-11-28 00 10 08" src="https://user-images.githubusercontent.com/35660884/49104307-a5cbfb80-f2a3-11e8-85c4-4d0337697d98.png">
<img width="1284" alt="screenshot 2018-11-28 00 11 51" src="https://user-images.githubusercontent.com/35660884/49104352-bb412580-f2a3-11e8-921f-b929ba32c5bf.png">

gljrDSnKjpXCfMbgSM. SCREEN SHOOT 
2.We have detected this domain to have malicious intent and have prevented you from interacting with it- SS attached

**Comment by Digital21** [comment]
Please find attached screenshot dated 28/11/18

**Comment by 409H** [comment]
Ah, you're talking about empowr. This domain has been blacklisted as it's asking users for private keys and sending them to their backend (unencrypted, but still - they shouldn't be asking for them)

See: https://github.com/409H/EtherAddressLookup/issues/1038

**Comment by 1Sinn** [comment]
I am a success coach and team leader on Empowr and with my best knowledge I can not see any wrong doing by Empowr. Once a citizen enters his private key Empowr will immeadetly encrypt the key, so that it is secured. For me it looks like the person who has started this false statement has no evidence about any wrong doing by Empowr and could be a angry bitter person, maybe a cheater who was deleted by Empowr! We do not permit cheating on Empowr! I love Empowr!

**Comment by 409H** [comment]
> Once a citizen enters his private key Empowr will immeadetly encrypt the key

It is not sent to Empowr encrypted at all. Asking for private keys to even touch the internet is wrong, asking for them to be shared is wrong.
