### ISSUE TITLE
omisego token check

### ISSUE THREAD

**Issue by mmmmyah** [409H/EtherAddressLookup#130]
Why is this website blacklisted ? thx

**Comment by 409H** [comment]
Which domain is it?

![image](https://user-images.githubusercontent.com/2313704/31810793-e973ed38-b574-11e7-9c26-fb4c38ef293f.png)

The above was blacklisted September 20, 2017 because it was a fake airdrop site, asking for your private keys.

![image](https://user-images.githubusercontent.com/2313704/31810947-94e081b8-b575-11e7-88f7-80d0aeb3106c.png)

See: https://github.com/409H/EtherAddressLookup/commit/384a2760ac2e87584bb763143d6707452295277d

See: https://etherscamdb.info/scam/2258/
