### ISSUE TITLE
Myetherwallet light client beta sync and password issue

### ISSUE THREAD

**Issue by harrytricky** [409H/EtherAddressLookup#155]
Hi there I am not a techie or developer but I will try my best to be concise about the problem.
Geth : 1.7.2
OS: OSX
Wallet: 0.9.2

Issue:
1.wallet does not sync fully , stuck at 99%  for a week and does not display my balance.
2.wallet with light client beta enabled sync fully and display my balance.
3.Couldnt transfer ethers to other account - I am very sure of my password for wallet and the main account yet it say wrong password.

The problem started after i updated to the new version of the wallet. 

screen shots as follows ;
1.normal sync
2.light client beta enabled sync
3.wallet transfer problem
4.ether scan
![screen shot 2017-11-01 at 10 38 02 am](https://user-images.githubusercontent.com/33272309/32258477-a0404528-bef5-11e7-95fa-48e614a85a51.png)
![screen shot 2017-11-01 at 10 40 06 am](https://user-images.githubusercontent.com/33272309/32258479-a324a266-bef5-11e7-8551-817c0d8c65f4.png)
![screen shot 2017-11-01 at 10 48 26 am](https://user-images.githubusercontent.com/33272309/32258483-a5dd3cca-bef5-11e7-8c2d-e1752bb3113c.png)
![screen shot 2017-11-01 at 10 40 58 am](https://user-images.githubusercontent.com/33272309/32258488-a84e66aa-bef5-11e7-860c-c15a9468ec86.png)

- I tried using the myether website. But I cannot see my balance in main account . kindly let me know what other information is required.

**Comment by 409H** [comment]
> 1.wallet does not sync fully , stuck at 99% for a week and does not display my balance.

Please can you open a ticket on the official repository for that project: https://github.com/ethereum/mist/issues or [read existing tickets](https://github.com/ethereum/mist/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20sync). Sorry I can't be of more help here, but I've never really used that software.

> 2.wallet with light client beta enabled sync fully and display my balance.

So this isn't an issue?

> 3.Couldnt transfer ethers to other account - I am very sure of my password for wallet and the main account yet it say wrong password.

It mustn't have the correct password. Try exporting your private key and signing a transaction offline (using geth or a gui like MyEtherWallet)

Your balance isn't being displayed on the GUI because you haven't sync'd with the blockchain fully (up to block 4362186 (the block etherscan says your ETH was received on)). Since the ETH is on the address, don't worry. When you have a client that is syncd or you use a managed node (like MyEtherWallet, or Infura, or QuikNode) then you will be able to see your balance and interact with it.

**Comment by 409H** [comment]
Please open a new issue if you are still having problems.
