### ISSUE TITLE
http://ethinvites.com

### ISSUE THREAD

**Issue by ser1974** [409H/EtherAddressLookup#305]
КАК ВКЛЮЧИТЬ ДОСТУП?

**Comment by ser1974** [comment]
КАК ВКЛЮЧИТЬ ДОСТУП?

**Comment by 409H** [comment]
Hi. I blacklisted the site because it asks you to refer x friends to the platform, then take surveys to get your funds out. The surveys generate the owner money, but you never get your funds out. 

It was reported a couple times through https://etherscamdb.info.

---

Здравствуй. Я занесен в черный список на сайте, потому что он просит вас отправить x друзей на платформу, а затем провести опросы, чтобы получить свои средства. Опросы генерируют деньги владельца, но вы никогда не получаете свои средства.

Сообщалось пару раз через https://etherscamdb.info.
- translate.google.com
