### ISSUE TITLE
I feel this domain is wrongly blacklisted (xn----ctbgeadglu0agbz4c.xn--p1ai)

### ISSUE THREAD

**Issue by klezar** [409H/EtherAddressLookup#895]
Hello!
I believe that the domain xn----ctbgeadglu0agbz4c.xn--p1ai is mistakenly entered in the database. The subdirectory of the gallery was deleted, the antivirus started complaining about it, although it was not published on the site.

**Comment by 409H** [comment]
This is because you have the option enabled to block all punycode domains. Please see the below image: 

![https://user-images.githubusercontent.com/2313704/39815987-bfd3cb5e-5391-11e8-90aa-6a6d3d0a9d25.png](https://user-images.githubusercontent.com/2313704/39815987-bfd3cb5e-5391-11e8-90aa-6a6d3d0a9d25.png)
